---
deployment:
  tasks:
    - export NODEBIN=/home/systema1/nodevenv/dev/20/bin
    - export DEPLOYPATH=/home/systema1/dev
    - $NODEBIN/npm install --prefix /home/systema1/dev
    - $NODEBIN/npm run build --prefix /home/systema1/dev
    - /bin/rsync -av --delete /home/systema1/dev/build/ $DEPLOYPATH/
    - /usr/local/bin/ea-nodejs-cli --app /home/systema1/nodevenv restart	